### ISSUE TITLE
Tipo BigInteger para campo com formato [0-9]{2}

### ISSUE THREAD

**Issue by imerljak** [samuelfac/portalunico.siscomex.gov.br#1]
Estou criando uma biblioteca de integração para a API do  Portal Único Siscomex e me deparei com uma dificuldade ao gerar o `XML` referente a entidade [Recebedor]( /samuelfac/portalunico.siscomex.gov.br/blob/master/src/main/java/br/gov/serpro/pucomex/cct/Recebedor.java).

Conforme meus testes com a api de validação, o formato exigido pela api para o campo `viaTransporte`  é `[0-9]{2}`, no entanto, quando tratamos de valores inteiros, os 0's a esquerda são desconsiderados, e não há como representar um valor inteiro dessa forma sem converte-lo para uma String (até onde sei..).

Logo, o mapeamento atual para a entidade `Recebedor` estaria incorreto para a formatação exigida.

Possívelmente este problema seria solucionado alterando o regex que valida essa campo para `[0-9]{1,2}`, ou alterando o campo `Recebedor.viaTransporte` para `String`

<pre><code>&ltsimpleType name="ViaTransporte">
    &ltrestriction base="integer">
        &ltpattern value="[0-9]{2}" /> &lt!-- Este pattern deveria ser [0-9]{1,2} -->
    &lt/restriction>
&lt/simpleType></code></pre>

**Comment by samuelfac** [comment]
Olá.

Eu não faço parte do desenvolvimento da API, apenas gerei as classes conforme os schemas disponíveis no site oficial: https://val.portalunico.siscomex.gov.br/docs/api/

Você deve abrir um chamado para a SERPRO pedindo essa atualização.
