### ISSUE TITLE
Dúvida.

### ISSUE THREAD

**Issue by fabiomazga** [samuelfac/portalunico.siscomex.gov.br#4]
Olá Samuel! Me chamo Fábio. Estou desenvolvendo uma API em Java para um empresa aduaniera no Brasil. Estou tendo dificuldade em cadastrar a duimp.
Estou na fase de testes.

#####################################

package com.example.ApiDuimp;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import javax.net.ssl.*;

public class DuimpCadastroTest {

    public static void main(String[] args) {
        String pfxPath = "C:/EclipseWorkspace/api-duimp/main/resources/certs/joaojose.pfx";
        String pfxPassword = "123456";
        String authUrl = "https://val.portalunico.siscomex.gov.br/portal/api/autenticar";
        String cadastroUrl = "https://val.portalunico.siscomex.gov.br/duimp-api/api/ext/duimp/";

        try {
            // Carregar o keystore com o certificado PFX
            KeyStore keyStore = KeyStore.getInstance("PKCS12");
            try (FileInputStream fis = new FileInputStream(pfxPath)) {
                keyStore.load(fis, pfxPassword.toCharArray());
            }

            // Configurar KeyManager para SSL
            KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            kmf.init(keyStore, pfxPassword.toCharArray());

            // Criar contexto SSL
            SSLContext sslContext = SSLContext.getInstance("TLS");
            sslContext.init(kmf.getKeyManagers(), new TrustManager[]{new X509TrustManager() {
                public java.security.cert.X509Certificate[] getAcceptedIssuers() { return null; }
                public void checkClientTrusted(java.security.cert.X509Certificate[] certs, String authType) { }
                public void checkServerTrusted(java.security.cert.X509Certificate[] certs, String authType) { }
            }}, new java.security.SecureRandom());

            HttpsURLConnection.setDefaultSSLSocketFactory(sslContext.getSocketFactory());
            HttpsURLConnection.setDefaultHostnameVerifier((hostname, session) -> true);

            // Autenticação
            HttpURLConnection authConnection = (HttpURLConnection) new URL(authUrl).openConnection();
            authConnection.setRequestMethod("POST");
            authConnection.setRequestProperty("Content-Type", "application/json");
            authConnection.setRequestProperty("Role-Type", "IMPEXP");
            authConnection.setDoOutput(true);

            // Enviar dados de autenticação (ajuste conforme necessário)
            try (OutputStream os = authConnection.getOutputStream()) {
                String authPayload = "{}";
                os.write(authPayload.getBytes(StandardCharsets.UTF_8));
            }

            int authResponseCode = authConnection.getResponseCode();
            if (authResponseCode == 200) {
                BufferedReader in = new BufferedReader(new InputStreamReader(authConnection.getInputStream()));
                String inputLine;
                StringBuilder response = new StringBuilder();
                while ((inputLine = in.readLine()) != null) {
                    response.append(inputLine);
                }
                in.close();

                // Exibir resposta de autenticação
                System.out.println("Resposta de Autenticação: " + response.toString());

                // Capturar tokens do cabeçalho
                String authToken = authConnection.getHeaderField("Authorization");
                String csrfToken = authConnection.getHeaderField("X-CSRF-Token");
                String setToken = authConnection.getHeaderField("set-token");

                // Se o token não estiver no cabeçalho, capturar do corpo da resposta
                if (authToken == null && response.toString().contains("token")) {
                    authToken = response.toString().replace("{\"token\":\"", "").replace("\"}", "").trim();
                    System.out.println("Token de Autenticação Capturado do Corpo (Authorization): " + authToken);
                }

                // Exibir tokens capturados
                if (authToken != null) {
                    authToken = authToken.trim();
                    System.out.println("Token de Autenticação Capturado (Authorization): [" + authToken + "]");
                } else {
                    System.out.println("Aviso: Nenhum token de autenticação capturado.");
                }

                if (csrfToken != null) {
                    csrfToken = csrfToken.trim();
                    System.out.println("X-CSRF-Token Capturado: [" + csrfToken + "]");
                } else {
                    System.out.println("Aviso: Nenhum X-CSRF-Token capturado.");
                }

                if (setToken != null) {
                    setToken = setToken.trim();
                    System.out.println("Set-Token Capturado: [" + setToken + "]");
                    // Usar o Set-Token como Bearer Token, caso necessário
                    authToken = "Bearer " + setToken;
                } else {
                    System.out.println("Aviso: Nenhum Set-Token capturado.");
                }

                // Solicitação de Cadastro usando os tokens capturados
                HttpURLConnection cadastroConnection = (HttpURLConnection) new URL(cadastroUrl).openConnection();
                cadastroConnection.setRequestMethod("POST");
                cadastroConnection.setRequestProperty("Content-Type", "application/json");
                cadastroConnection.setRequestProperty("Accept", "application/json");
                if (authToken != null) {
                    cadastroConnection.setRequestProperty("Authorization", authToken);
                }
                if (csrfToken != null) {
                    cadastroConnection.setRequestProperty("X-CSRF-Token", csrfToken);
                }
                cadastroConnection.setDoOutput(true);

                // Dados para o POST de cadastro
                String cadastroData = "{"
                        + "\"identificacao\": {"
                        + "\"importador\": {"
                        + "\"tipoImportador\": \"CNPJ\","
                        + "\"ni\": \"09521059000108\""
                        + "},"
                        + "\"informacaoComplementar\": \"Texto complementando informações sobre a Duimp.\""
                        + "},"
                        + "\"carga\": {"
                        + "\"tipoIdentificacaoCarga\": \"CE\","
                        + "\"identificacao\": \"999999999999901\","
                        + "\"unidadeDeclarada\": {\"codigo\": \"0717600\"},"
                        + "\"seguro\": {\"codigoMoedaNegociada\": \"USD\", \"valorMoedaNegociada\": 1500.00}"
                        + "},"
                        + "\"documentos\": {"
                        + "\"documentosInstrucao\": [{"
                        + "\"tipo\": {\"codigo\": \"50\"},"
                        + "\"palavrasChave\": [{\"codigo\": \"1\", \"valor\": \"9999999999\"}]"
                        + "}],"
                        + "\"processos\": [],"
                        + "\"declaracoesExportacaoEstrangeira\": []"
                        + "}"
                        + "}";

                try (OutputStream os = cadastroConnection.getOutputStream()) {
                    os.write(cadastroData.getBytes(StandardCharsets.UTF_8));
                }

                int cadastroResponseCode = cadastroConnection.getResponseCode();
                if (cadastroResponseCode == 200 || cadastroResponseCode == 201) {
                    BufferedReader cadastroIn = new BufferedReader(new InputStreamReader(cadastroConnection.getInputStream()));
                    String cadastroLine;
                    StringBuilder cadastroResponse = new StringBuilder();
                    while ((cadastroLine = cadastroIn.readLine()) != null) {
                        cadastroResponse.append(cadastroLine);
                    }
                    cadastroIn.close();
                    System.out.println("Resposta do Cadastro: " + cadastroResponse.toString());
                } else {
                    System.out.println("Erro durante o cadastro: Código " + cadastroResponseCode);
                    BufferedReader errorReader = new BufferedReader(new InputStreamReader(cadastroConnection.getErrorStream()));
                    String errorLine;
                    StringBuilder errorResponse = new StringBuilder();
                    while ((errorLine = errorReader.readLine()) != null) {
                        errorResponse.append(errorLine);
                    }
                    errorReader.close();
                    System.out.println("Erro Detalhado: " + errorResponse.toString());
                }
            } else {
                System.out.println("Erro durante a autenticação: Código " + authResponseCode);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

#########################
está dando o erro:

Resposta de Autenticação: {"token":"Nnnz7iNcLuqOFOU6tuHCD1mwVDZ+Nj3Cx+Yrpb2YozeX3CnsnccXqrrMztMmpAj7EzVl/oPpDiU="}
Token de Autenticação Capturado do Corpo (Authorization): Nnnz7iNcLuqOFOU6tuHCD1mwVDZ+Nj3Cx+Yrpb2YozeX3CnsnccXqrrMztMmpAj7EzVl/oPpDiU=
Token de Autenticação Capturado (Authorization): [Nnnz7iNcLuqOFOU6tuHCD1mwVDZ+Nj3Cx+Yrpb2YozeX3CnsnccXqrrMztMmpAj7EzVl/oPpDiU=]
X-CSRF-Token Capturado: [Nnnz7iNcLuqJBtkDHYx3txVfI4Yrj1C6fRG57P62CIyNPktLf7obQo9kI/cyXv4Yj2Bs0Y6+9cQ=]
Set-Token Capturado: [eyJhbGciOiJSUzI1NiJ9.eyJleHRlbnNhbyI6IiIsInN1YiI6Ijc0Njk2NjYxNzY4IiwidGlwbyI6IlBGIiwiYW1iaWVudGUiOiJUUkUiLCJpcCI6IjE3Ny4xMjQuMjAxLjE2MiIsImlzcyI6IlBSSVYiLCJpZGNjIjo2NjA0LCJub21lIjoiSk9BTyBKT1NFIERBIFNJTFZBIiwiaXBPcmlnZW0iOiIxNzcuMTI0LjIwMS4xNjIiLCJkZXNjcmljYW8iOiJKT0FPIEpPU0UgREEgU0lMVkEiLCJwZXJmaXMiOiJINHNJQUFBQUFBQUFBRVZUVFk4YU1RejlRNUY2MzVzbk1VUGFUSkpOTW9DNjJnTUNwTzJoeXdvNFZLcjYzMnM3SHh3QVQ4aTg5X3llX2ZiM2NUdC0zby1uNi1YLThxWjFTUW5MQWw0VmNORjZyWU9SVW1jWDEwbEZyUkc4Q2ZVc2VQNmJYOEpEOGFGSXVYcGI3RTlsVmp6UUJmcVJrcUM0cEF2QXI4MnpxbHd6LXFLTVhSak1XSkJUbmVtaHFKM1ZqSkFOQ2kxUm9iRWRZV2U5MHRZWHdrMUZpeHhTSGRISUtaWEp4Q2Z1MGhGQ1JVZzV1SktJRFF5WXZZZVNLbkh3Q2JYU2pnVmtyeGRCZ0dqcGtTZ21sck5nVVFrd0UwSk1ZUmlDaDBGTWNpcGJZcjNOaDRSWlNuQ0ZmV2oyMFplY0pzamlqc3N6MFhSaTBySkdzbThfX1NEY2dtbTRIa1V2SkNRYktsdGVjeERIUWdSNnRTbllXbEl3ZktUV29mRDdMSnk0TmxReUY3ZE9CQVpxZ0liQXZPVUxGQ24wQ3hRVmowVUhjN1pOU05HaFh0QlBCR0dyWlNxTDVxaDZhcEl3R05TUWNRUm9OcDJDN1JmUFBUVTNkX3U1ckEwNS0td2lSSHlHdlJHYm1IaDFJdEw2elV5T3NidVRlOFZsYWdneDJkM29JbUgzREEteFJnVjFaSW1ZWnBwVFkyWDB4TDNKcVlNcEpIWW40dGFLTzcyTDJKdG5vN29jR2d5ZUhCUDJrRjZmRFdrRm5xYUJQNm5iTjVxUGRxd0NyOWhZeHEzTlVtYTdyQVZZQTN4ZmpYYjFiZ3daTkcxcjRUWTliMnUxdW1pb2swUGJRY3ZkY2FtOUlYMHgxUjJnSWFwUjBWcmE0Uzc5emJvTVJwQ2xLYkpyS2JRaGxDeWJjR3hpYUY1WlRPZnlkV2xhYW5XNEM4OXBBNU1zNjR5d0MyM1g2T2RkX1RxX1NCaFJuU18zMDR2OV9YVzlQWTduNi0wYl9obWx1ZHlfanFlUDQtZmo4dV85UF94S2NXUFVCQUFBIiwiY3JlZGVuY2lhbCI6NiwiY3BmIjoiNzQ2OTY2NjE3NjgiLCJpYXQiOjE3MzE0MjExNzIsImNvbnRyb2xlIjo3LCJoYXNoIjoiZmQ5MjQ4ZmU3YjFkY2EwMjFkOGVlODg4MWNkMzg5OGYifQ.CD4NbSUK2CfWR2HdKQ_OAo32L_kpowsTfGqm8CgPZWPCFXsnIrQJnopWKesoT6YJm82BZMMfNi4n8oQP09Uj2s_hCkFJ-Z8QZXSI0MxeH-D7TsTgMR758FS0JIsR9SiugcU3fAuBjqwSG1rYxqGOOe3BAiS3CSCvzoNGLjiAlZLU7Cru2EZSxCw2N1RvIScudcrf9qxw0bHAOL5jkXQcDz27IPskFL7bz6ACJJvukXoZGQfHtEYVFABL_Uqc04HEgYtJCtyy6VvxQljnF-MLBxZQ6-WcDd6lWpK8A2UiREeEtxNvFH82Kos2dVEP9v7oFZGMwv0oLUez1ePmoicy3g]
Erro durante o cadastro: Código 401
Erro Detalhado: {"message":"O Header X-CSRF-Token não é válido.","tag":"[DIMP-ONYENEMFZ2]","date":"2024-11-12T11:19:32","detail":[],"severity":"ERROR","info":{"mnemonico":"DIMP","sistema":"Declaração Única de Importação","ambiente":"TRE","visao":"PRIV","url":"/duimp-api/api/ext/duimp/","trackerId":"1ilPK3x2G4"}}

#########################
sou desenvolvedor junior
se puder me dar uma força pra resolver esse problema ficaria agradecido.
abç

**Comment by samuelfac** [comment]
O erro me parece bastante claro, procure trabalhar o json como objeto ao invés de texto usando o [GSON](https://github.com/google/gson).

Conforme documentação disponível em [https://docs.portalunico.siscomex.gov.br/introducao-api-publica/](https://docs.portalunico.siscomex.gov.br/introducao-api-publica/) você pode entrar em contato diretamente com eles para sanar suas dúvidas:
```
Caso haja dúvidas relacionadas ao Novo Processo de Exportações, envie-as ao [Comex Responde](http://www.comexresponde.gov.br/) (campo "Assunto Geral" opção "Sistemas e ferramentas de apoio" e campo "Assunto Específico" opção "Portal Único Siscomex").

Para problemas relacionados à TI entre em contato com a [Central Serpro de Atendimento](https://cssinter.serpro.gov.br/SCCDPortalWEB/pages/dynamicPortal.jsf?ITEMNUM=2176) (no campo de "Serviço" escolher a opção "PORTAL ÚNICO SISCOMEX - PUCOMEX").
```
