### ISSUE TITLE
Como usar

### ISSUE THREAD

**Issue by NicolasFelippe** [samuelfac/portalunico.siscomex.gov.br#5]
Poderia comentar como usar essa api?

**Comment by samuelfac** [comment]
Toda a documentação de utilização das APIs estão no site oficial: [https://docs.portalunico.siscomex.gov.br/](https://docs.portalunico.siscomex.gov.br/)

Este projeto contém as classes javas geradas a partir de todos os swaggers disponíveis no site oficial.
